---
- s3_bucket:
    documentation:
      short_description: Create and manage S3 buckets
      description: Create and manage S3 buckets (list, create, update, describe, delete).
- logs_log_group:
    documentation:
      short_description: Create and manage log groups
      description: Create and manage log groups (list, create, update, describe, delete).
- iam_role:
    documentation:
      short_description: Create and manage roles
      description: Creates and manages new roles for your AWS account (list, create, update, describe, delete).
- backup_backup_vault:
    documentation:
      short_description: Create and manage logical containers where backups are stored
      description: Creates and manages logical containers where backups are stored (create, update, describe, delete).
- backup_framework:
    documentation:
      short_description: Create and manage frameworks with one or more controls 
      description: Creates and manages frameworks with one or more controls (list, create, update, describe, delete).
- backup_report_plan:
    documentation:
      short_description: Create and manage report plans
      description: Creates and manages report plans (list, create, update, describe, delete).
- eks_cluster:
    documentation:
      short_description: Create and manages Amazon EKS control planes
      description: Create and manage Amazon EKS control planes (list, create, update, describe, delete).  
- lambda_code_signing_config:
    documentation:
      short_description: Code signing for AWS Lambda
      description: Creates and manage code signing for AWS Lambda (list, create, update, describe, delete).
- lambda_event_source_mapping:
    documentation:
      short_description: Create a mapping between an event source and an AWS Lambda function
      description: Create a mapping between an event source and an AWS Lambda function (list, create, update, describe, delete).
- lambda_function:
    documentation:
      short_description: Create and manage Lambda functions
      description: Creates and manage Lambda functions (list, create, update, describe, delete).
- logs_query_definition:
    documentation:
      short_description: Create and manage query definitions
      description: Creates and manage query definitions for CloudWatch Logs Insights (list, create, update, describe, delete).
- logs_resource_policy:
    documentation:
      short_description: Create and manage resource policies
      description: Creates and manage resource policies that allows other AWS services to put log events to the account (list, create, update, describe, delete).
- rdsdb_proxy:
    documentation:
      short_description: Create and manage DB proxies
      description: Creates and manage DB proxies (list, create, update, describe, delete).
- redshift_cluster:
    documentation:
      short_description: Create and manage clusters
      description: Creates and manage clusters (list, create, update, describe, delete).
- redshift_event_subscription:
    documentation:
      short_description: Create and manage Amazon Redshift event notification subscriptions
      description: Creates and manage Amazon Redshift event notification subscriptions (list, create, update, describe, delete).
- s3_access_point:
    documentation:
      short_description: Create and manage Amazon S3 access points to use to access S3 buckets
      description: Create and manage Amazon S3 access points to use to access S3 buckets (list, create, update, describe, delete).
- s3_multi_region_access_point:
    documentation:
      short_description: Create and manage Amazon S3 Multi-Region Access Points
      description: Create and manage Amazon S3 Multi-Region Access Points (list, create, update, describe, delete).
- s3_multi_region_access_point_policy:
    documentation:
      short_description: Manage Amazon S3 access policies
      description: Applie and manage Amazon S3 access policies to an Amazon S3 Multi-Region Access Points (list, create, update, describe, delete).
- s3_object_lambda_access_point:
    documentation:
      short_description: Create and manage Object Lambda Access Points used to access S3 buckets
      description: Create and manage Object Lambda Access Points used to access S3 buckets (list, create, update, describe, delete).
- s3_object_lambda_access_point_policy:
    documentation:
      short_description: Specifies the Object Lambda Access Point resource policy document
      description: Create and manage Object Lambda Access Point resource policy document (create, update, describe, delete).
- dynamo_db_global_table:
- eks_fargate_profile:
- eks_addon:
#- wa_fv2_web_acl:
- wa_fv2_web_ip_set:
- wa_fv2_regex_pattern_set:
